name: "Wherein The Chicken"
markdown: kramdown
highlighter: rouge
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
whereinthechicken:
   author: "Nash Reilly"
   email: "nrc.reilly@gmail.com"
